name: adhd_task_triage
description: "A task triage app for ADHD users, designed to help them prioritize and manage their tasks effectively."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  uuid: ^4.5.1
  google_fonts: ^6.1.0
  animated_text_kit: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:


  uses-material-design: true
