name: ADHD Task Triage
description: "A task triage app for ADHD users, designed to help them prioritize and manage their tasks effectively."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  uuid: ^4.5.1
  google_fonts: ^6.1.0
  animated_text_kit: ^4.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  url_launcher: ^6.2.6
  supabase_flutter: ^2.8.0
  crypto: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
